# Generated by Django 5.0.2 on 2024-02-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint', models.CharField(choices=[('ANY', 'Любой из ответов'), ('ALL', 'Все ответы'), ('NONE', 'Нет')], default='NONE', max_length=4)),
                ('multiple_answers', models.CharField(choices=[('SINGLE', 'Один из списка'), ('MULTIPLE', 'Несколько из списка')], default='SINGLE', max_length=8)),
                ('text', models.CharField(max_length=100)),
                ('required_answers', models.ManyToManyField(to='survey.answer', verbose_name='Необходимые предыдущие ответы')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
