# Generated by Django 5.0.2 on 2024-02-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='possible_answers',
            field=models.ManyToManyField(related_name='possible_answers', to='survey.answer', verbose_name='Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='constraint',
            field=models.CharField(choices=[('ANY', 'Любой из ответов'), ('ALL', 'Все ответы'), ('NONE', 'Нет')], default='NONE', max_length=4, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='question',
            name='multiple_answers',
            field=models.CharField(choices=[('SINGLE', 'Один из списка'), ('MULTIPLE', 'Несколько из списка')], default='SINGLE', max_length=8, verbose_name='Выбор ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required_answers',
            field=models.ManyToManyField(related_name='required_answers', to='survey.answer', verbose_name='Необходимые предыдущие ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст вопроса:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
