# Generated by Django 5.0.2 on 2024-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_answer_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required_answers',
            field=models.ManyToManyField(blank=True, related_name='required_answers', to='survey.answer', verbose_name='Необходимые предыдущие ответы'),
        ),
    ]
